name: SimTrader CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  server-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      
      - name: Install Dependencies
        run: cd server && npm ci
      - name: Prisma
        run: npx prisma generate
      - name: Type Check
        run: cd server && npm run type-check

  app-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      
      - name: Install Dependencies
        run: cd app && npm ci
      
      - name: Lint
        run: cd app && npm run lint
      
      - name: Type Check
        run: cd app && npm run type-check
    
  build-and-push:
    needs: [server-check] # Запускаем только если сервер прошел проверки
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Пушим образы только из главной ветки
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Server Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/DockerFile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simtrader-backend:latest

  deploy:
    needs: build-and-push # Запускаем только после успешной загрузки образа
    runs-on: ubuntu-latest
    steps:
      - name: Update Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/SimTrader # Путь к папке с docker-compose.yml на сервере
            docker-compose pull backend
            docker-compose up -d