name: SimTrader CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  server-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      
      - name: Install Dependencies
        run: cd server && npm ci
      - name: Prisma
        run: cd server && npx prisma generate
      - name: Type Check
        run: cd server && npm run type-check

  app-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      
      - name: Install Dependencies
        run: cd app && npm ci
      
      - name: Lint
        run: cd app && npm run lint
      
      - name: Type Check
        run: cd app && npm run type-check
    
 

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
  
          script: |
            cd ~/simtrader # Путь к папке с docker-compose.yml на сервере
            sudo docker compose down
            git pull
            sudo docker compose up -d --build